name: Update Stock Prices

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:     # Allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas yfinance openpyxl

      - name: Run update script
        run: python update_prices.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "SKV Sheet-1-Updated.xlsx"
          git commit -m "Auto-update stock prices [skip ci]" || echo "No changes to commit"
          git push

